"""initial schema

Revision ID: 9a7bae7cc24d
Revises: 
Create Date: 2026-07-03 18:40:25.235183

"""
from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401 — autogenerate renders Vector columns
import sqlmodel  # noqa: F401 — string columns render as sqlmodel AutoString
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7bae7cc24d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any vector(768) column can be created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('major_genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('director', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distributor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mpaa_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creative_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('imdb_votes', sa.Integer(), nullable=True),
    sa.Column('rotten_tomatoes_rating', sa.Integer(), nullable=True),
    sa.Column('production_budget', sa.BigInteger(), nullable=True),
    sa.Column('worldwide_gross', sa.BigInteger(), nullable=True),
    sa.Column('running_time_min', sa.Integer(), nullable=True),
    sa.Column('runtime_imputed', sa.Boolean(), nullable=False),
    sa.Column('budget_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decade', sa.Integer(), nullable=True),
    sa.Column('blockbuster_flag', sa.Boolean(), nullable=False),
    sa.Column('augmented_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pipeline_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

    # Approximate-nearest-neighbour index for cosine similarity search
    # (autogenerate cannot express the hnsw method / opclass / storage params).
    op.execute(
        """
        CREATE INDEX ix_movies_embedding
        ON movies USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('movies')
    # ### end Alembic commands ###
